name: weinds
description: "Weincode design system WeinDs."
version: 0.0.1
homepage: https://weincode.dev/

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/bg/bg-categories.png
    - assets/images/brand/cohete.png
    - assets/images/brand/weincode-logo-silver.png
    - assets/images/illustrations/space.png
    - assets/images/illustrations/love.png
    - assets/images/illustrations/explorar tecnologia.png
    - assets/images/illustrations/atom.png
    - assets/images/illustrations/molecules.png
    - assets/images/illustrations/organisms.png
    - assets/images/illustrations/programando.png
    - assets/images/illustrations/design.png
    - assets/images/illustrations/design-white.png
    - assets/images/illustrations/asesoria.png
    - assets/images/illustrations/templates.png
    - assets/images/illustrations/action.png
  fonts:
    - family: Cocogoose
      fonts:
        - asset: assets/fonts/Cocogoose-Pro-Bold-trial.ttf
        - asset: assets/fonts/Cocogoose-Pro-Light-trial.ttf
        - asset: assets/fonts/Cocogoose-Pro-Semilight-trial.ttf
